(function initPresetLibrary(globalScope) {
  const preset = (meta, values) => ({ ...meta, values, realismScore: meta.realismScore || 8.5 });

  const PRESET_LIBRARY = [
    // CRT
    preset({ id: "crt-consumer-1987", name: "Consumer CRT Living Room (1987)", description: "Composite-fed living room set with moderate bloom and tube softness.", type: "CRT", era: "1980s", signalFamily: "analog", damageLevel: "mild", tags: ["consumer-tv", "composite", "home-viewing"], signalChain: "Broadcast camera → NTSC composite encode → cable tuner → consumer shadow-mask CRT", historicalContext: "Typical suburban TV setup before S-Video adoption.", sortOrder: 10, realismScore: 9.2 }, { scanlineStrength: 0.46, phosphorMask: 0.42, barrelDistortion: -0.03, bloom: 0.44, flicker: 0.12, chromaticAberration: 0.22, noise: 0.16, maskScale: 1, maskType: "phosphor" }),
    preset({ id: "crt-pvm-clean", name: "Sony PVM Studio Monitor", description: "Tight aperture-grille response with minimal drift.", type: "CRT", era: "1990s", signalFamily: "analog", damageLevel: "clean", tags: ["pvm", "broadcast", "reference-monitor"], signalChain: "Betacam SP deck → component routing → Sony PVM/BVM monitor", historicalContext: "Used in post and control rooms where signal integrity mattered.", sortOrder: 11, realismScore: 9.5 }, { scanlineStrength: 0.24, phosphorMask: 0.58, barrelDistortion: -0.01, bloom: 0.18, flicker: 0.05, chromaticAberration: 0.05, noise: 0.08, maskScale: 1, maskType: "aperture" }),
    preset({ id: "crt-arcade-cabinet", name: "Arcade Cabinet Tube", description: "High-drive arcade chassis with punchy bloom and corner distortion.", type: "CRT", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["arcade", "jamma", "coin-op"], signalChain: "Arcade PCB RGB output → arcade monitor chassis → curved CRT glass", historicalContext: "Common in cabinets with heavy daily runtime.", sortOrder: 12, realismScore: 9.1 }, { scanlineStrength: 0.41, phosphorMask: 0.46, barrelDistortion: -0.06, bloom: 0.56, flicker: 0.14, chromaticAberration: 0.14, noise: 0.14, maskScale: 1, maskType: "slot" }),
    preset({ id: "crt-hotel-set-1978", name: "Hotel CRT Feed (1978)", description: "Soft RF distributed set with visible interference and ghosting.", type: "CRT", era: "1970s", signalFamily: "analog", damageLevel: "medium", tags: ["rf", "distribution", "hospitality"], signalChain: "Broadcast feed → building RF distribution amp → aging coax run → consumer CRT", historicalContext: "Long coax runs caused softness and multipath-like echoes.", sortOrder: 13, realismScore: 8.7 }, { scanlineStrength: 0.42, phosphorMask: 0.36, barrelDistortion: -0.05, bloom: 0.49, flicker: 0.16, chromaticAberration: 0.26, noise: 0.3, advancedGhosting: 0.28, advancedRfInterference: 0.24, advancedCrossColor: 0.2, maskType: "dot" }),
    preset({ id: "crt-late-life-tube", name: "Worn Consumer Tube", description: "A late-life CRT with low focus and unstable drive.", type: "CRT", era: "2000s", signalFamily: "analog", damageLevel: "medium", tags: ["aging-tube", "focus-drift", "home-tv"], signalChain: "DVD player composite out → aging CRT with worn flyback/high-voltage section", historicalContext: "Older sets drifted in focus and color registration.", sortOrder: 14, realismScore: 8.8 }, { scanlineStrength: 0.48, phosphorMask: 0.34, barrelDistortion: -0.04, bloom: 0.52, flicker: 0.18, chromaticAberration: 0.32, noise: 0.22, advancedFocusBreathing: 0.22, advancedWhiteBalanceDrift: 0.16, maskType: "phosphor" }),
    preset({ id: "crt-kiosk-monitor", name: "Retail Kiosk CRT", description: "Public display tube with bright drive and slight convergence issues.", type: "CRT", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["kiosk", "public-display", "looped-video"], signalChain: "VHS loop deck → RF modulator/composite splitter → kiosk CRT", historicalContext: "Retail loops ran hot and often looked overdriven.", sortOrder: 15, realismScore: 8.6 }, { scanlineStrength: 0.39, phosphorMask: 0.4, barrelDistortion: -0.03, bloom: 0.58, flicker: 0.1, chromaticAberration: 0.18, noise: 0.19, advancedGhosting: 0.16, maskType: "phosphor" }),
    preset({ id: "crt-broadcast-conf-monitor", name: "Conference Room Trinitron", description: "Professional monitor fed from distribution amplifier, low artifact profile.", type: "CRT", era: "2000s", signalFamily: "hybrid", damageLevel: "clean", tags: ["trinitron", "corporate", "sd-monitor"], signalChain: "Digital SDI ingest → analog component monitor out → Trinitron monitor", historicalContext: "Late CRT-era conference and QC rooms.", sortOrder: 16, realismScore: 8.9 }, { scanlineStrength: 0.22, phosphorMask: 0.5, barrelDistortion: -0.01, bloom: 0.2, flicker: 0.04, chromaticAberration: 0.06, noise: 0.08, maskType: "aperture" }),

    // VHS / Analog tape
    preset({ id: "vhs-home-1989", name: "Home VHS Recording (1989)", description: "Single-generation home tape played on a consumer VCR.", type: "VHS", era: "1980s", signalFamily: "analog", damageLevel: "mild", tags: ["vhs", "home-video", "single-gen"], signalChain: "Consumer camcorder → VHS SP recording → household VCR playback → CRT capture", historicalContext: "Common domestic recordings with modest chroma bleed.", sortOrder: 30, realismScore: 9.3 }, { scanlineStrength: 0.51, phosphorMask: 0.28, barrelDistortion: -0.08, bloom: 0.58, chromaticAberration: 0.46, noise: 0.3, advancedLineJitter: 0.19, advancedTimebaseWobble: 0.25, advancedHeadSwitching: 0.38, advancedChromaDelay: 0.31, advancedCrossColor: 0.28, advancedInterlacing: 0.22, advancedTimestampOSD: 0.4, maskType: "phosphor" }),
    preset({ id: "vhs-rental-3rd-gen", name: "Rental Tape Dub (3rd Gen)", description: "Copy-of-copy VHS rental with strong generation loss.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "heavy", tags: ["vhs", "dub", "generation-loss"], signalChain: "Telecine master → rental dub chain (x3) → misaligned deck playback → CRT", historicalContext: "Late-life rental copies often had muddy luma/chroma separation.", sortOrder: 31, realismScore: 9.1 }, { scanlineStrength: 0.58, phosphorMask: 0.2, barrelDistortion: -0.1, bloom: 0.68, chromaticAberration: 0.58, noise: 0.44, advancedLineJitter: 0.31, advancedTimebaseWobble: 0.44, advancedHeadSwitching: 0.55, advancedChromaDelay: 0.48, advancedCrossColor: 0.52, advancedDropouts: 0.46, advancedGenerationLoss: 0.72, advancedTimestampOSD: 0.6, maskType: "phosphor" }),
    preset({ id: "vhs-public-access-1994", name: "Public Access VHS Master", description: "Community station VHS ingest with unstable edits and chroma lag.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "medium", tags: ["public-access", "vhs-master", "community-tv"], signalChain: "Local studio camera → VHS line cut → cable access playback → home CRT capture", historicalContext: "Low-budget stations depended on VHS master chains.", sortOrder: 32, realismScore: 8.9 }, { scanlineStrength: 0.47, phosphorMask: 0.3, bloom: 0.5, chromaticAberration: 0.34, noise: 0.32, advancedLineJitter: 0.17, advancedTimebaseWobble: 0.26, advancedHeadSwitching: 0.2, advancedChromaDelay: 0.33, advancedCrossColor: 0.35, advancedDropouts: 0.24, advancedTimestampOSD: 0.66, maskType: "phosphor" }),
    preset({ id: "vhs-ep-slp", name: "Extended Play VHS (SLP)", description: "Long-play tape with lower bandwidth and increased noise floor.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "medium", tags: ["slp", "extended-play", "home-recording"], signalChain: "Broadcast recording in SLP mode → consumer VCR playback → CRT", historicalContext: "SLP often traded duration for image stability and detail.", sortOrder: 33, realismScore: 9.0 }, { scanlineStrength: 0.54, phosphorMask: 0.24, bloom: 0.62, chromaticAberration: 0.52, noise: 0.41, advancedLineJitter: 0.28, advancedTimebaseWobble: 0.36, advancedHeadSwitching: 0.47, advancedChromaDelay: 0.42, advancedDropouts: 0.31, advancedGenerationLoss: 0.3, maskType: "phosphor" }),
    preset({ id: "vhs-tracking-drift", name: "Mis-tracked VHS Playback", description: "Poor tracking alignment produces tearing and head-switching noise.", type: "VHS", era: "1980s", signalFamily: "analog", damageLevel: "heavy", tags: ["tracking", "vcr", "alignment"], signalChain: "Home VHS recording → playback on mismatched deck → CRT", historicalContext: "Inter-machine tolerances often exposed tracking errors.", sortOrder: 34, realismScore: 8.8 }, { scanlineStrength: 0.57, phosphorMask: 0.22, bloom: 0.6, chromaticAberration: 0.49, noise: 0.42, advancedLineJitter: 0.34, advancedTimebaseWobble: 0.41, advancedHeadSwitching: 0.68, advancedDropouts: 0.52, advancedTapeCrease: 0.36, maskType: "phosphor" }),
    preset({ id: "svhs-edit-suite", name: "S-VHS Edit Suite", description: "Higher-bandwidth S-VHS chain with cleaner chroma and moderate analog texture.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "clean", tags: ["s-vhs", "prosumer", "edit-suite"], signalChain: "Hi8 source → S-VHS recorder over S-Video → CRT monitor", historicalContext: "Prosumer editors used S-VHS to preserve detail.", sortOrder: 35, realismScore: 9.1 }, { scanlineStrength: 0.4, phosphorMask: 0.33, bloom: 0.42, chromaticAberration: 0.2, noise: 0.2, advancedLineJitter: 0.08, advancedTimebaseWobble: 0.14, advancedHeadSwitching: 0.14, advancedChromaDelay: 0.12, advancedDropouts: 0.1, maskType: "aperture" }),
    preset({ id: "umatic-newsroom", name: "U-matic Newsroom Copy", description: "Early ENG cassette copy with timebase instability and chroma errors.", type: "VHS", era: "1970s", signalFamily: "analog", damageLevel: "medium", tags: ["u-matic", "eng", "newsroom"], signalChain: "Studio camera → U-matic field cassette → newsroom dub → CRT", historicalContext: "U-matic copies showed pronounced chroma/luma misregistration.", sortOrder: 36, realismScore: 8.8 }, { scanlineStrength: 0.48, phosphorMask: 0.25, bloom: 0.46, chromaticAberration: 0.4, noise: 0.35, advancedTimebaseWobble: 0.32, advancedChromaDelay: 0.44, advancedCrossColor: 0.34, advancedDropouts: 0.25, advancedGenerationLoss: 0.38, maskType: "dot" }),
    preset({ id: "betacam-sp-field", name: "Betacam SP Field Tape", description: "Professional analog component acquisition with restrained defects.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["betacam-sp", "field-production", "broadcast"], signalChain: "ENG camera → Betacam SP tape → studio deck → PVM monitor", historicalContext: "Betacam SP held up better than consumer tape formats.", sortOrder: 37, realismScore: 9.4 }, { scanlineStrength: 0.31, phosphorMask: 0.44, bloom: 0.28, chromaticAberration: 0.12, noise: 0.16, advancedTimebaseWobble: 0.08, advancedDropouts: 0.06, advancedInterlacing: 0.2, maskType: "aperture" }),
    preset({ id: "vhs-wedding-1992", name: "Wedding VHS Master (1992)", description: "Event videography tape with occasional camera auto-exposure pumping.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["event-video", "wedding", "camcorder"], signalChain: "Camcorder composite out → VHS recorder → family CRT playback", historicalContext: "Ceremony videos often exhibit mixed lighting and AGC pumping.", sortOrder: 38, realismScore: 8.9 }, { scanlineStrength: 0.5, phosphorMask: 0.3, bloom: 0.55, chromaticAberration: 0.35, noise: 0.27, advancedExposurePump: 0.28, advancedWhiteBalanceDrift: 0.22, advancedLineJitter: 0.14, advancedHeadSwitching: 0.24, advancedTimestampOSD: 0.48, maskType: "phosphor" }),
    preset({ id: "vhs-sixth-gen-trade", name: "Tape Trading Copy (6th Gen)", description: "Fan-traded multi-generation tape with severe blur and noise buildup.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "extreme", tags: ["tape-trading", "multi-generation", "bootleg"], signalChain: "Live source → repeated VHS dub chain (x6+) → consumer playback", historicalContext: "Underground exchange scenes produced very degraded but watchable copies.", sortOrder: 39, realismScore: 8.5 }, { scanlineStrength: 0.62, phosphorMask: 0.18, bloom: 0.72, chromaticAberration: 0.64, noise: 0.56, advancedTimebaseWobble: 0.5, advancedHeadSwitching: 0.64, advancedDropouts: 0.58, advancedGenerationLoss: 0.86, advancedTapeCrease: 0.42, maskType: "phosphor" }),
    preset({ id: "vhs-preserved-master", name: "Archived VHS Master (Well Stored)", description: "Well-preserved tape transfer with mild aging signatures.", type: "VHS", era: "1980s", signalFamily: "analog", damageLevel: "clean", tags: ["archive", "preserved", "transfer"], signalChain: "Original VHS master → serviced deck with TBC → modern capture", historicalContext: "Properly stored tapes can remain stable with minor noise.", sortOrder: 40, realismScore: 9.0 }, { scanlineStrength: 0.43, phosphorMask: 0.22, bloom: 0.38, chromaticAberration: 0.2, noise: 0.2, advancedDropouts: 0.08, advancedGenerationLoss: 0.1, advancedChromaDelay: 0.14, maskType: "none" }),

    // Broadcast
    preset({ id: "broadcast-offair-antenna", name: "Off-Air Analog Broadcast", description: "Roof antenna reception with RF snow and chroma crawl.", type: "Broadcast", era: "1980s", signalFamily: "analog", damageLevel: "medium", tags: ["off-air", "antenna", "ntsc"], signalChain: "Broadcast camera → transmitter → household antenna reception → CRT", historicalContext: "Atmospherics and local interference shaped image quality.", sortOrder: 60, realismScore: 9.2 }, { scanlineStrength: 0.44, phosphorMask: 0.36, bloom: 0.5, chromaticAberration: 0.33, noise: 0.29, advancedRfInterference: 0.42, advancedCrossColor: 0.34, advancedGhosting: 0.18, advancedInterlacing: 0.24, maskType: "phosphor" }),
    preset({ id: "broadcast-cable-1996", name: "Cable Feed (1996)", description: "Analog cable chain with moderate recompression and occasional ghosting.", type: "Broadcast", era: "1990s", signalFamily: "hybrid", damageLevel: "mild", tags: ["cable", "headend", "analog"], signalChain: "Studio feed → cable headend remodulation → coax drop → consumer CRT", historicalContext: "Cable headend remodulation introduced mild softness and ghosts.", sortOrder: 61, realismScore: 8.9 }, { scanlineStrength: 0.39, phosphorMask: 0.33, bloom: 0.41, chromaticAberration: 0.24, noise: 0.22, advancedGhosting: 0.16, advancedCrossColor: 0.2, advancedRfInterference: 0.16, maskType: "phosphor" }),
    preset({ id: "broadcast-studio-line", name: "Studio Program Line", description: "Clean baseband studio transmission monitored on reference CRT.", type: "Broadcast", era: "1990s", signalFamily: "analog", damageLevel: "clean", tags: ["studio", "program-line", "reference"], signalChain: "Studio camera chain → switcher → baseband SD distribution → PVM", historicalContext: "Internal feeds were typically cleaner than consumer delivery.", sortOrder: 62, realismScore: 9.4 }, { scanlineStrength: 0.22, phosphorMask: 0.52, bloom: 0.18, chromaticAberration: 0.05, noise: 0.07, advancedInterlacing: 0.2, maskType: "aperture" }),
    preset({ id: "broadcast-public-access-cable", name: "Public Access Cable Slot", description: "Low-budget cable slot with mixed source quality and tape wear.", type: "Broadcast", era: "1990s", signalFamily: "analog", damageLevel: "medium", tags: ["public-access", "cable", "community"], signalChain: "Community camera/tape sources → local cable playout → consumer CRT", historicalContext: "Mixed ingest chains yielded visible inconsistencies.", sortOrder: 63, realismScore: 8.8 }, { scanlineStrength: 0.45, phosphorMask: 0.3, bloom: 0.48, chromaticAberration: 0.34, noise: 0.31, advancedDropouts: 0.2, advancedChromaDelay: 0.26, advancedTimestampOSD: 0.3, advancedRfInterference: 0.24, maskType: "phosphor" }),
    preset({ id: "broadcast-satellite-early-digital", name: "Early Digital Satellite Feed", description: "Early MPEG satellite decode with mosquito noise and block edges.", type: "Broadcast", era: "2000s", signalFamily: "digital", damageLevel: "medium", tags: ["satellite", "mpeg2", "set-top-box"], signalChain: "Digital broadcast uplink → MPEG2 satellite decode → set-top composite out → CRT", historicalContext: "First-gen STBs exposed compression artifacts in motion.", sortOrder: 64, realismScore: 9.0 }, { scanlineStrength: 0.28, phosphorMask: 0.26, bloom: 0.24, chromaticAberration: 0.14, noise: 0.15, advancedQuantization: 0.26, advancedMacroBlocking: 0.22, advancedFrameStutter: 0.08, advancedInterlacing: 0.18, maskType: "phosphor" }),
    preset({ id: "broadcast-master-control-archive", name: "Master Control Aircheck", description: "Aircheck VHS made from master control output with restrained issues.", type: "Broadcast", era: "1980s", signalFamily: "analog", damageLevel: "mild", tags: ["aircheck", "master-control", "vhs-capture"], signalChain: "Studio output → master control → off-air VHS aircheck → CRT playback", historicalContext: "Airchecks were reference copies, usually not heavily damaged.", sortOrder: 65, realismScore: 8.8 }, { scanlineStrength: 0.42, phosphorMask: 0.3, bloom: 0.45, chromaticAberration: 0.28, noise: 0.24, advancedHeadSwitching: 0.12, advancedRfInterference: 0.26, advancedTimestampOSD: 0.08, maskType: "phosphor" }),
    preset({ id: "broadcast-late-night-weak-signal", name: "Late-Night Weak Signal Capture", description: "Marginal off-air capture with high RF instability.", type: "Broadcast", era: "1970s", signalFamily: "analog", damageLevel: "heavy", tags: ["weak-signal", "antenna", "rf-noise"], signalChain: "Broadcast transmitter fringe zone → weak antenna lock → consumer VCR capture", historicalContext: "Fringe reception could oscillate between watchable and noisy.", sortOrder: 66, realismScore: 8.6 }, { scanlineStrength: 0.5, phosphorMask: 0.28, bloom: 0.56, chromaticAberration: 0.38, noise: 0.46, advancedRfInterference: 0.58, advancedGhosting: 0.3, advancedFrameStutter: 0.14, maskType: "phosphor" }),

    // Camcorder / CCTV
    preset({ id: "camcorder-hi8-family", name: "Hi8 Family Camcorder", description: "Handheld Hi8 footage with auto white balance drift and mild instability.", type: "Camcorder", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["hi8", "family-video", "handheld"], signalChain: "Hi8 camcorder sensor → Hi8 tape → deck playback → CRT", historicalContext: "Hi8 improved detail but still showed analog chroma behavior.", sortOrder: 80, realismScore: 9.2 }, { scanlineStrength: 0.4, phosphorMask: 0.32, bloom: 0.44, chromaticAberration: 0.22, noise: 0.2, advancedTimebaseWobble: 0.14, advancedHeadSwitching: 0.2, advancedWhiteBalanceDrift: 0.3, advancedExposurePump: 0.22, advancedTimestampOSD: 0.36, maskType: "phosphor" }),
    preset({ id: "camcorder-video8-lowlight", name: "Video8 Indoor Low Light", description: "Early Video8 grain and pumping under tungsten lighting.", type: "Camcorder", era: "1980s", signalFamily: "analog", damageLevel: "medium", tags: ["video8", "low-light", "consumer"], signalChain: "Video8 camcorder → tape playback → CRT", historicalContext: "Low-light indoor scenes produced noisy, warm shifts.", sortOrder: 81, realismScore: 8.8 }, { scanlineStrength: 0.46, phosphorMask: 0.3, bloom: 0.52, chromaticAberration: 0.3, noise: 0.34, advancedExposurePump: 0.34, advancedWhiteBalanceDrift: 0.28, advancedFocusBreathing: 0.2, advancedTimestampOSD: 0.52, maskType: "phosphor" }),
    preset({ id: "camcorder-minidv-2003", name: "MiniDV Family Trip (2003)", description: "DV tape with sharp luma, interlacing, and mild block noise.", type: "Camcorder", era: "2000s", signalFamily: "hybrid", damageLevel: "mild", tags: ["minidv", "dv25", "family-trip"], signalChain: "MiniDV camcorder → FireWire ingest / analog playback to CRT", historicalContext: "MiniDV looked cleaner but revealed digital breakup in motion.", sortOrder: 82, realismScore: 9.1 }, { scanlineStrength: 0.28, phosphorMask: 0.38, bloom: 0.28, chromaticAberration: 0.14, noise: 0.18, advancedInterlacing: 0.34, advancedQuantization: 0.14, advancedFrameStutter: 0.1, advancedTimestampOSD: 0.45, maskType: "aperture" }),
    preset({ id: "camcorder-shoulder-prosumer", name: "Prosumer Shoulder Cam", description: "Wedding/event shoulder cam with stable tape transport and AGC behavior.", type: "Camcorder", era: "1990s", signalFamily: "analog", damageLevel: "clean", tags: ["prosumer", "event", "shoulder-cam"], signalChain: "Prosumer camcorder → S-VHS dub master → CRT monitoring", historicalContext: "Prosumer rigs produced cleaner color than basic handycams.", sortOrder: 83, realismScore: 8.7 }, { scanlineStrength: 0.36, phosphorMask: 0.34, bloom: 0.36, chromaticAberration: 0.18, noise: 0.18, advancedExposurePump: 0.18, advancedTimestampOSD: 0.28, maskType: "phosphor" }),
    preset({ id: "camcorder-vhs-c-1991", name: "VHS-C Handycam (1991)", description: "Compact VHS-C home footage with transport flutter and warm chroma.", type: "Camcorder", era: "1990s", signalFamily: "analog", damageLevel: "medium", tags: ["vhs-c", "handycam", "home-video"], signalChain: "VHS-C camcorder → adapter playback in VCR → CRT", historicalContext: "VHS-C was convenient but often less stable in repeated playback.", sortOrder: 83.2, realismScore: 8.8 }, { scanlineStrength: 0.49, phosphorMask: 0.28, bloom: 0.54, chromaticAberration: 0.38, noise: 0.33, advancedLineJitter: 0.2, advancedTimebaseWobble: 0.26, advancedHeadSwitching: 0.3, advancedTimestampOSD: 0.5, maskType: "phosphor" }),
    preset({ id: "camcorder-hi8-edited-master", name: "Hi8 Edited Master", description: "Two-pass home edit retaining camcorder character with added generation softness.", type: "Camcorder", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["hi8", "edited", "home-production"], signalChain: "Hi8 camcorder → linear edit to Hi8 master → CRT playback", historicalContext: "Home edits introduced slight additional chroma loss and timing wobble.", sortOrder: 83.4, realismScore: 8.9 }, { scanlineStrength: 0.42, phosphorMask: 0.31, bloom: 0.46, chromaticAberration: 0.24, noise: 0.24, advancedTimebaseWobble: 0.18, advancedChromaDelay: 0.2, advancedDropouts: 0.14, advancedWhiteBalanceDrift: 0.2, maskType: "phosphor" }),
    preset({ id: "cctv-analog-mono-1991", name: "Analog CCTV Multiplexer (1991)", description: "Monochrome security feed with frame skipping and timestamp burn-in.", type: "CCTV", era: "1990s", signalFamily: "analog", damageLevel: "medium", tags: ["cctv", "monochrome", "security"], signalChain: "CCTV tube camera → analog multiplexer → time-lapse VCR → monitor", historicalContext: "Security systems often used low frame rates and OSD timestamps.", sortOrder: 84, realismScore: 9.3 }, { scanlineStrength: 0.16, phosphorMask: 0.14, bloom: 0.1, chromaticAberration: 0.04, noise: 0.24, advancedFrameStutter: 0.48, advancedCctvMonochrome: 0.74, advancedTimestampOSD: 0.78, advancedRfInterference: 0.15, maskType: "none" }),
    preset({ id: "cctv-dvr-2008", name: "Early DVR Security Export", description: "Low-bitrate digital DVR export from fixed surveillance camera.", type: "CCTV", era: "2000s", signalFamily: "digital", damageLevel: "heavy", tags: ["dvr", "h264", "security-export"], signalChain: "CCD CCTV camera → DVR encoder → USB export", historicalContext: "Early DVR systems leaned on aggressive compression and frame dropping.", sortOrder: 85, realismScore: 8.9 }, { scanlineStrength: 0.08, phosphorMask: 0.06, bloom: 0.06, chromaticAberration: 0.03, noise: 0.22, advancedFrameStutter: 0.44, advancedQuantization: 0.4, advancedMacroBlocking: 0.34, advancedTimestampOSD: 0.7, advancedCctvMonochrome: 0.38, maskType: "none" }),

    // Web / digital
    preset({ id: "web-realplayer-1999", name: "RealPlayer Stream (1999)", description: "Early internet stream with heavy temporal stutter and quantization.", type: "Web", era: "1990s", signalFamily: "digital", damageLevel: "heavy", tags: ["realplayer", "dial-up", "streaming"], signalChain: "Analog source digitized → RealVideo encode → low-bandwidth playback capture", historicalContext: "Dial-up era codecs produced block noise and frame pacing issues.", sortOrder: 100, realismScore: 9.0 }, { scanlineStrength: 0.02, phosphorMask: 0.02, bloom: 0.05, chromaticAberration: 0.03, noise: 0.1, advancedFrameStutter: 0.46, advancedQuantization: 0.52, advancedMacroBlocking: 0.36, advancedGenerationLoss: 0.22, maskType: "none" }),
    preset({ id: "web-wmv-2002", name: "Windows Media Portal (2002)", description: "Corporate portal WMV with softened detail and macroblocking.", type: "Web", era: "2000s", signalFamily: "digital", damageLevel: "medium", tags: ["wmv", "portal-video", "early-web"], signalChain: "DV source → WMV transcode → embedded browser player", historicalContext: "Enterprise streaming portals used low/medium bitrate WMV profiles.", sortOrder: 101, realismScore: 8.8 }, { scanlineStrength: 0.03, phosphorMask: 0.02, bloom: 0.05, chromaticAberration: 0.02, noise: 0.08, advancedQuantization: 0.4, advancedMacroBlocking: 0.3, advancedFrameStutter: 0.2, maskType: "none" }),
    preset({ id: "web-youtube-2006", name: "YouTube Upload (2006)", description: "First-generation web upload with staircase edges and crushed gradients.", type: "Web", era: "2000s", signalFamily: "digital", damageLevel: "medium", tags: ["youtube", "flash", "h263"], signalChain: "Consumer camera source → Flash-era transcode → browser playback", historicalContext: "Early YouTube emphasized small file sizes over clarity.", sortOrder: 102, realismScore: 9.1 }, { scanlineStrength: 0.02, phosphorMask: 0.01, bloom: 0.04, chromaticAberration: 0.02, noise: 0.06, advancedQuantization: 0.44, advancedMacroBlocking: 0.32, advancedGenerationLoss: 0.18, advancedFrameStutter: 0.18, maskType: "none" }),
    preset({ id: "web-viral-reencode-2010", name: "Viral Re-encode Loop (2010)", description: "Repeated download/re-upload chain leading to cumulative digital loss.", type: "Web", era: "2010s", signalFamily: "digital", damageLevel: "heavy", tags: ["re-encode", "viral", "generation-loss"], signalChain: "Original upload → repeated transcoding across platforms → local capture", historicalContext: "Cross-platform reposting compounded compression artifacts.", sortOrder: 103, realismScore: 8.6 }, { scanlineStrength: 0.01, phosphorMask: 0, bloom: 0.03, chromaticAberration: 0.01, noise: 0.08, advancedQuantization: 0.48, advancedMacroBlocking: 0.42, advancedGenerationLoss: 0.36, advancedFrameStutter: 0.22, maskType: "none" }),
    preset({ id: "web-lowbandwidth-livestream", name: "Low-Bandwidth Livestream", description: "Severe bitrate adaptation with macroblocking bursts.", type: "Web", era: "2010s", signalFamily: "digital", damageLevel: "extreme", tags: ["livestream", "adaptive-bitrate", "packet-loss"], signalChain: "Digital camera → live encoder → unstable network playback", historicalContext: "Congested uploads produced abrupt block fields and stutter.", sortOrder: 104, realismScore: 8.5 }, { scanlineStrength: 0, phosphorMask: 0, bloom: 0.02, chromaticAberration: 0.01, noise: 0.12, advancedQuantization: 0.62, advancedMacroBlocking: 0.58, advancedFrameStutter: 0.48, advancedGenerationLoss: 0.28, maskType: "none" }),

    // Archive
    preset({ id: "archive-damaged-vhs-box", name: "Poorly Stored VHS Archive", description: "Humidity damage causing dropout clusters and crease events.", type: "Archive", era: "1990s", signalFamily: "analog", damageLevel: "extreme", tags: ["archive-damage", "humidity", "dropouts"], signalChain: "VHS master storage failure → compromised deck playback → digital preservation capture", historicalContext: "Improper storage accelerated oxide shedding and binder issues.", sortOrder: 120, realismScore: 9.0 }, { scanlineStrength: 0.54, phosphorMask: 0.24, bloom: 0.6, chromaticAberration: 0.5, noise: 0.5, advancedDropouts: 0.64, advancedTapeCrease: 0.58, advancedGenerationLoss: 0.5, advancedTimebaseWobble: 0.42, maskType: "none" }),
    preset({ id: "archive-betacam-shed", name: "Betacam Oxide Shed Recovery", description: "Intermittent signal collapse during emergency transfer.", type: "Archive", era: "1980s", signalFamily: "analog", damageLevel: "heavy", tags: ["betacam", "oxide-shed", "recovery"], signalChain: "Betacam archive tape → restoration deck with cleaning passes → transfer capture", historicalContext: "Archivists often perform risky one-pass transfers on unstable stock.", sortOrder: 121, realismScore: 8.7 }, { scanlineStrength: 0.4, phosphorMask: 0.26, bloom: 0.44, chromaticAberration: 0.34, noise: 0.42, advancedDropouts: 0.52, advancedTapeCrease: 0.32, advancedTimebaseWobble: 0.36, advancedInterlacing: 0.24, maskType: "none" }),
    preset({ id: "archive-kinescope-16mm", name: "16mm Kinescope Archive", description: "Film-recorded broadcast with gate weave, dust, and projector flicker.", type: "Archive", era: "1950s", signalFamily: "hybrid", damageLevel: "medium", tags: ["kinescope", "16mm", "broadcast-archive"], signalChain: "Live CRT broadcast monitor → 16mm film recording → telecine digitization", historicalContext: "Kinescopes preserved live TV before videotape matured.", sortOrder: 122, realismScore: 9.3 }, { scanlineStrength: 0.2, phosphorMask: 0.12, bloom: 0.24, flicker: 0.1, chromaticAberration: 0.1, noise: 0.24, advancedFilmGrain: 0.5, advancedFilmDust: 0.32, advancedFilmScratches: 0.28, advancedFilmGateWeave: 0.34, advancedFilmHalation: 0.22, maskType: "film16mm" }),
    preset({ id: "archive-umatic-institutional", name: "Institutional U-matic Archive", description: "Educational tape transfer with moderate wear and stable sync.", type: "Archive", era: "1970s", signalFamily: "analog", damageLevel: "medium", tags: ["u-matic", "institutional", "transfer"], signalChain: "U-matic training tape → serviced playback deck → ADC capture", historicalContext: "Institutional libraries often retained U-matic for decades.", sortOrder: 123, realismScore: 8.8 }, { scanlineStrength: 0.38, phosphorMask: 0.2, bloom: 0.34, chromaticAberration: 0.26, noise: 0.3, advancedDropouts: 0.34, advancedChromaDelay: 0.3, advancedGenerationLoss: 0.24, maskType: "none" })
  ];

  globalScope.CRT_PRESET_LIBRARY = PRESET_LIBRARY;
})(window);
