const OFF_ADVANCED = {
  advancedLineJitter: 0,
  advancedTimebaseWobble: 0,
  advancedHeadSwitching: 0,
  advancedChromaDelay: 0,
  advancedCrossColor: 0,
  advancedDropouts: 0,
  advancedGhosting: 0,
  advancedInterlacing: 0,
};

export const PRESETS = {
  "Consumer TV": {
    scanlineStrength: 0.45,
    phosphorMask: 0.36,
    barrelDistortion: -0.28,
    bloom: 0.45,
    flicker: 0.1,
    chromaticAberration: 0.3,
    noise: 0.2,
    ...OFF_ADVANCED,
  },
  "PVM/BVM": {
    scanlineStrength: 0.25,
    phosphorMask: 0.6,
    barrelDistortion: -0.08,
    bloom: 0.2,
    flicker: 0.04,
    chromaticAberration: 0.08,
    noise: 0.07,
    ...OFF_ADVANCED,
  },
  "RF Broadcast": {
    scanlineStrength: 0.42,
    phosphorMask: 0.38,
    barrelDistortion: -0.24,
    bloom: 0.48,
    flicker: 0.14,
    chromaticAberration: 0.36,
    noise: 0.24,
    advancedLineJitter: 0.18,
    advancedTimebaseWobble: 0.24,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.2,
    advancedCrossColor: 0.25,
    advancedDropouts: 0.12,
    advancedGhosting: 0.14,
    advancedInterlacing: 0.18,
  },
  "VHS EP": {
    scanlineStrength: 0.5,
    phosphorMask: 0.24,
    barrelDistortion: -0.22,
    bloom: 0.62,
    flicker: 0.16,
    chromaticAberration: 0.5,
    noise: 0.3,
    advancedLineJitter: 0.26,
    advancedTimebaseWobble: 0.36,
    advancedHeadSwitching: 0.44,
    advancedChromaDelay: 0.35,
    advancedCrossColor: 0.4,
    advancedDropouts: 0.34,
    advancedGhosting: 0.32,
    advancedInterlacing: 0.3,
  },
  "Hi8 Camcorder": {
    scanlineStrength: 0.38,
    phosphorMask: 0.3,
    barrelDistortion: -0.14,
    bloom: 0.42,
    flicker: 0.1,
    chromaticAberration: 0.22,
    noise: 0.18,
    advancedLineJitter: 0.08,
    advancedTimebaseWobble: 0.14,
    advancedHeadSwitching: 0.18,
    advancedChromaDelay: 0.22,
    advancedCrossColor: 0.2,
    advancedDropouts: 0.14,
    advancedGhosting: 0.22,
    advancedInterlacing: 0.24,
  },
  "Arcade Cabinet": {
    scanlineStrength: 0.44,
    phosphorMask: 0.56,
    barrelDistortion: -0.2,
    bloom: 0.58,
    flicker: 0.07,
    chromaticAberration: 0.18,
    noise: 0.11,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.12,
    advancedInterlacing: 0,
  },
};
