(function initPresetLibrary(globalScope) {
  const preset = (meta, values) => ({ ...meta, values });

  const PRESET_LIBRARY = [
    preset({ id: "crt-consumer-1987", name: "Consumer TV", description: "Composite-fed consumer CRT with moderate bloom and scanline response.", type: "CRT", era: "1980s", signalFamily: "analog", damageLevel: "mild", tags: ["consumer-tv", "crt", "composite"], signalChain: "Broadcast/cable source → composite decode → consumer CRT", historicalContext: "Typical living-room CRT profile.", sortOrder: 10, realismScore: 9.1 }, {}),
    preset({ id: "crt-pvm-bvm", name: "PVM/BVM", description: "Reference monitor look with tighter focus and reduced artifacts.", type: "CRT", era: "1990s", signalFamily: "analog", damageLevel: "clean", tags: ["pvm", "bvm", "reference"], signalChain: "Studio source → component routing → PVM/BVM", historicalContext: "Professional monitoring chain.", sortOrder: 11, realismScore: 9.3 }, {}),
    preset({ id: "crt-arcade", name: "Arcade", description: "High-drive arcade chassis with vivid bloom.", type: "CRT", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["arcade", "rgb"], signalChain: "Arcade PCB RGB → arcade CRT chassis", historicalContext: "Coin-op arcade cabinet displays.", sortOrder: 12, realismScore: 9.0 }, {}),

    preset({ id: "vhs-home-80s", name: "Late-80s Home VHS", description: "Single-generation home VHS playback profile.", type: "VHS", era: "1980s", signalFamily: "analog", damageLevel: "medium", tags: ["vhs", "home-video"], signalChain: "Camcorder source → VHS SP recording → consumer VCR playback", historicalContext: "Common family recording chain.", sortOrder: 30, realismScore: 9.0 }, {}),
    preset({ id: "vhs-rental-dub", name: "90s Rental Tape (3rd Gen Dub)", description: "Multi-generation rental dub with generation loss.", type: "VHS", era: "1990s", signalFamily: "analog", damageLevel: "heavy", tags: ["vhs", "dub", "generation-loss"], signalChain: "Master tape → repeated VHS dubs → playback", historicalContext: "Late rental ecosystem artifact profile.", sortOrder: 31, realismScore: 8.8 }, {}),
    preset({ id: "cam-hi8", name: "Hi8 Vacation Cam", description: "Hi8 family camcorder playback look.", type: "Camcorder", era: "1990s", signalFamily: "analog", damageLevel: "mild", tags: ["hi8", "camcorder"], signalChain: "Hi8 camcorder tape → deck playback → CRT", historicalContext: "Consumer travel recordings.", sortOrder: 40, realismScore: 9.0 }, {}),
    preset({ id: "cam-minidv", name: "MiniDV Family Cam (2002)", description: "MiniDV interlaced consumer recording with mild digital breakup.", type: "Camcorder", era: "2000s", signalFamily: "hybrid", damageLevel: "mild", tags: ["minidv", "dv"], signalChain: "MiniDV camcorder → DV decode/playback → display", historicalContext: "Early 2000s household camcorder look.", sortOrder: 41, realismScore: 9.0 }, {}),

    preset({ id: "broadcast-offair", name: "Off-Air Analog Broadcast", description: "RF reception with interference bands and mild chroma instability.", type: "Broadcast", era: "1980s", signalFamily: "analog", damageLevel: "medium", tags: ["off-air", "rf", "broadcast"], signalChain: "Broadcast transmission → antenna reception → consumer TV", historicalContext: "Analog terrestrial reception path.", sortOrder: 50, realismScore: 9.1 }, {}),
    preset({ id: "broadcast-access", name: "Public Access Archive", description: "Public access playout with mixed source quality.", type: "Broadcast", era: "1990s", signalFamily: "analog", damageLevel: "medium", tags: ["public-access", "broadcast"], signalChain: "Local station ingest → tape playout → cable feed", historicalContext: "Community broadcast archive feel.", sortOrder: 51, realismScore: 8.8 }, {}),

    preset({ id: "web-2006", name: "Early Web Rip (2006)", description: "Early web transcode with quantization and macroblocking.", type: "Web", era: "2000s", signalFamily: "digital", damageLevel: "medium", tags: ["web", "compression", "2006"], signalChain: "Analog/digital source → low-bitrate web encode → browser playback", historicalContext: "Flash/early H.264 era transcodes.", sortOrder: 60, realismScore: 9.0 }, {}),
    preset({ id: "cctv-dump", name: "Security Camera Dump", description: "Security export with timestamp OSD and frame cadence loss.", type: "CCTV", era: "2000s", signalFamily: "digital", damageLevel: "heavy", tags: ["cctv", "security", "osd"], signalChain: "CCTV camera → DVR encode → export", historicalContext: "Consumer/commercial surveillance dump profile.", sortOrder: 61, realismScore: 8.9 }, {}),

    preset({ id: "archive-damaged", name: "Damaged Archive Recovery", description: "Aged analog master with dropouts and repair artifacts.", type: "Archive", era: "1980s", signalFamily: "hybrid", damageLevel: "extreme", tags: ["archive", "recovery", "damage"], signalChain: "Aged tape master → unstable deck transfer → digital cleanup", historicalContext: "Archive rescue transfer scenario.", sortOrder: 70, realismScore: 8.8 }, {}),
    preset({ id: "film-silent", name: "Silent Film 1920s", description: "Monochrome film transfer with scratches and gate weave.", type: "Film", era: "1950s", signalFamily: "hybrid", damageLevel: "medium", tags: ["film", "silent-era", "archive"], signalChain: "Film print → telecine transfer", historicalContext: "Historic film-to-video transfer characteristics.", sortOrder: 80, realismScore: 8.8 }, {}),
    preset({ id: "film-technicolor", name: "Technicolor Print 1950s", description: "Saturated print transfer with halation and grain.", type: "Film", era: "1950s", signalFamily: "hybrid", damageLevel: "mild", tags: ["technicolor", "film"], signalChain: "Color film print → optical/telecine capture", historicalContext: "Mid-century color print transfer profile.", sortOrder: 81, realismScore: 8.9 }, {}),
    preset({ id: "film-super8", name: "Super 8 Home Reel 1970s", description: "Home reel transfer with grain and mechanical instability.", type: "Film", era: "1970s", signalFamily: "hybrid", damageLevel: "medium", tags: ["super8", "home-reel"], signalChain: "Super 8 capture → projector/telecine transfer", historicalContext: "Consumer film archive style.", sortOrder: 82, realismScore: 9.0 }, {}),
    preset({ id: "film-kinescope", name: "16mm Broadcast Kinescope", description: "CRT-recorded film archive with mixed scan and film artifacts.", type: "Archive", era: "1950s", signalFamily: "hybrid", damageLevel: "medium", tags: ["kinescope", "16mm", "broadcast"], signalChain: "Broadcast CRT monitor → 16mm film recording → transfer", historicalContext: "Pre-videotape broadcast archival process.", sortOrder: 83, realismScore: 9.1 }, {})
  ];

  globalScope.CRT_PRESET_LIBRARY = PRESET_LIBRARY;
})(window);
