const OFF_ADVANCED = {
  advancedLineJitter: 0,
  advancedTimebaseWobble: 0,
  advancedHeadSwitching: 0,
  advancedChromaDelay: 0,
  advancedCrossColor: 0,
  advancedDropouts: 0,
  advancedGhosting: 0,
  advancedInterlacing: 0,
};

export const PRESETS = {
  "Consumer TV": {
    scanlineStrength: 0.45,
    phosphorMask: 0.36,
    barrelDistortion: -0.109,
    bloom: 0.45,
    flicker: 0.1,
    chromaticAberration: 0.3,
    noise: 0.2,
    ...OFF_ADVANCED,
  },
  "PVM/BVM": {
    scanlineStrength: 0.25,
    phosphorMask: 0.6,
    barrelDistortion: -0.031,
    bloom: 0.2,
    flicker: 0.04,
    chromaticAberration: 0.08,
    noise: 0.07,
    ...OFF_ADVANCED,
  },
  "RF Broadcast": {
    scanlineStrength: 0.42,
    phosphorMask: 0.38,
    barrelDistortion: -0.094,
    bloom: 0.48,
    flicker: 0.14,
    chromaticAberration: 0.36,
    noise: 0.24,
    advancedLineJitter: 0.18,
    advancedTimebaseWobble: 0.24,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0.2,
    advancedCrossColor: 0.25,
    advancedDropouts: 0.12,
    advancedGhosting: 0.14,
    advancedInterlacing: 0.18,
  },
  "VHS EP": {
    scanlineStrength: 0.5,
    phosphorMask: 0.24,
    barrelDistortion: -0.086,
    bloom: 0.62,
    flicker: 0.16,
    chromaticAberration: 0.5,
    noise: 0.3,
    advancedLineJitter: 0.26,
    advancedTimebaseWobble: 0.36,
    advancedHeadSwitching: 0.44,
    advancedChromaDelay: 0.35,
    advancedCrossColor: 0.4,
    advancedDropouts: 0.34,
    advancedGhosting: 0.32,
    advancedInterlacing: 0.3,
  },
  "Hi8 Camcorder": {
    scanlineStrength: 0.38,
    phosphorMask: 0.3,
    barrelDistortion: -0.055,
    bloom: 0.42,
    flicker: 0.1,
    chromaticAberration: 0.22,
    noise: 0.18,
    advancedLineJitter: 0.08,
    advancedTimebaseWobble: 0.14,
    advancedHeadSwitching: 0.18,
    advancedChromaDelay: 0.22,
    advancedCrossColor: 0.2,
    advancedDropouts: 0.14,
    advancedGhosting: 0.22,
    advancedInterlacing: 0.24,
  },
  "Arcade Cabinet": {
    scanlineStrength: 0.44,
    phosphorMask: 0.56,
    barrelDistortion: -0.078,
    bloom: 0.58,
    flicker: 0.07,
    chromaticAberration: 0.18,
    noise: 0.11,
    advancedLineJitter: 0,
    advancedTimebaseWobble: 0,
    advancedHeadSwitching: 0,
    advancedChromaDelay: 0,
    advancedCrossColor: 0,
    advancedDropouts: 0,
    advancedGhosting: 0.12,
    advancedInterlacing: 0,
  },
  "Retro Pixel LCD": {
    scanlineStrength: 0.08,
    phosphorMask: 0.04,
    barrelDistortion: 0,
    bloom: 0.08,
    flicker: 0.02,
    chromaticAberration: 0.03,
    noise: 0.04,
    ...OFF_ADVANCED,
    maskType: "dot",
  },
  "Cyberpunk OLED": {
    scanlineStrength: 0.14,
    phosphorMask: 0.12,
    barrelDistortion: -0.012,
    bloom: 0.68,
    flicker: 0.03,
    chromaticAberration: 0.06,
    noise: 0.05,
    advancedGhosting: 0.04,
    ...OFF_ADVANCED,
    maskType: "none",
  },
  "Streaming Compression": {
    scanlineStrength: 0.18,
    phosphorMask: 0.1,
    barrelDistortion: 0,
    bloom: 0.2,
    flicker: 0.03,
    chromaticAberration: 0.07,
    noise: 0.12,
    advancedLineJitter: 0.01,
    advancedChromaDelay: 0.02,
    advancedDropouts: 0.08,
    advancedGhosting: 0.06,
    advancedInterlacing: 0.04,
    maskType: "aperture",
  },
  "Digital Surveillance": {
    scanlineStrength: 0.22,
    phosphorMask: 0.16,
    barrelDistortion: 0,
    bloom: 0.12,
    flicker: 0.02,
    chromaticAberration: 0.04,
    noise: 0.18,
    advancedLineJitter: 0.02,
    advancedTimebaseWobble: 0.02,
    advancedChromaDelay: 0.03,
    advancedDropouts: 0.12,
    advancedGhosting: 0.03,
    advancedInterlacing: 0.12,
    maskType: "none",
  },
  "Silent Film 1920s": {
    scanlineStrength: 0,
    phosphorMask: 0,
    barrelDistortion: 0,
    bloom: 0.08,
    flicker: 0.24,
    chromaticAberration: 0,
    noise: 0.34,
    ...OFF_ADVANCED,
    advancedFilmGrain: 0.72,
    advancedFilmDust: 0.46,
    advancedFilmScratches: 0.58,
    advancedFilmGateWeave: 0.54,
    advancedFilmHalation: 0.28,
    maskType: "none",
  },
  "Technicolor Print 1950s": {
    scanlineStrength: 0.04,
    phosphorMask: 0.08,
    barrelDistortion: -0.01,
    bloom: 0.36,
    flicker: 0.05,
    chromaticAberration: 0.12,
    noise: 0.14,
    ...OFF_ADVANCED,
    advancedGhosting: 0.08,
    advancedFilmGrain: 0.44,
    advancedFilmDust: 0.18,
    advancedFilmScratches: 0.12,
    advancedFilmGateWeave: 0.24,
    advancedFilmHalation: 0.62,
    maskType: "dot",
  },
  "Super 8 Home Reel 1970s": {
    scanlineStrength: 0.06,
    phosphorMask: 0.04,
    barrelDistortion: -0.02,
    bloom: 0.42,
    flicker: 0.18,
    chromaticAberration: 0.18,
    noise: 0.29,
    ...OFF_ADVANCED,
    advancedFilmGrain: 0.76,
    advancedFilmDust: 0.38,
    advancedFilmScratches: 0.28,
    advancedFilmGateWeave: 0.46,
    advancedFilmHalation: 0.4,
    maskType: "filmSuper8",
  },
  "16mm Broadcast Kinescope": {
    scanlineStrength: 0.22,
    phosphorMask: 0.18,
    barrelDistortion: -0.046,
    bloom: 0.31,
    flicker: 0.08,
    chromaticAberration: 0.11,
    noise: 0.22,
    advancedLineJitter: 0.09,
    advancedTimebaseWobble: 0.14,
    advancedDropouts: 0.08,
    advancedGhosting: 0.12,
    advancedInterlacing: 0.2,
    advancedFilmGrain: 0.48,
    advancedFilmDust: 0.22,
    advancedFilmScratches: 0.24,
    advancedFilmGateWeave: 0.32,
    advancedFilmHalation: 0.24,
    maskType: "film16mm",
  },
};
